### ISSUE TITLE
Error: Unable to determine textarea instance

### ISSUE THREAD

**Issue by FearedFusionX** [Pitu/Magane#98]
So I recently installed this plugin for my Vencord client and when I tried to send a sticker, it gave me this error:
![image](https://github.com/user-attachments/assets/e2adf250-f021-4ba9-b0f7-c875101d780b)

Here's what happened:
https://github.com/user-attachments/assets/26ace0f3-0c91-4dc7-b927-713a1b0190db

Is it possible for you to take a look at this?

**Comment by Pitu** [comment]
@FearedFusionX could you try disabling all your other plugins and css first to see if it's a problem with one of those?

**Comment by FearedFusionX** [comment]
Interesting, it started working but I don't know what is causing it. here's the logs that I am getting:

```
magane.vencord.js:2209 Error: Unable to determine textarea instance.
    at Ji (magane.vencord.js:2128:33)
    at Array.<anonymous> (magane.vencord.js:2844:488)
    at HTMLImageElement.p (magane.vencord.js:977:14)
Ji @ magane.vencord.js:2209
(anonymous) @ magane.vencord.js:2844
p @ magane.vencord.js:977
```

**Comment by FearedFusionX** [comment]
I've also confirmed it's not the CSS that is affecting it

**Comment by BobbyWibowo** [comment]
Are you still getting this? It's either an edge-case, or you were enrolled to an early preview of Discord's updates that haven't gone live for the rest of us yet. I'm unable to replicate this as of right now.

**Comment by FearedFusionX** [comment]
Still getting this, here is my list of plugins:
![image](https://github.com/user-attachments/assets/8dee740b-d33f-4189-87d2-571dfbb2d548)

**Comment by BobbyWibowo** [comment]
are those all supposed to be third-party plugins not available from vencord's built-in repo? then unfortunately that's far outside the support scope

in short, one of them must be modifying the text area a bit more extensively than usual*, for our method to fail. but yeah, we wont be able to inspect those

* some plugins such as simple char counters, or other plugins that simply add more buttons to the text area, are supposed to play nice with magane already

**Comment by FearedFusionX** [comment]
yeah, they are third party plugins, I just am not sure what could be causing it
